
[project]
name = "campushire-backend"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "fastapi",
    "uvicorn",
    "sqlalchemy>=2.0",
    "asyncpg",
    "alembic",
    "pydantic>=2",
    "pydantic[email]",
    "pydantic-settings",
    "python-paseto",
    "argon2-cffi",
    "httpx",
    "pypdf",
    "minio",
    "python-multipart",
    "apscheduler",
    "psycopg2-binary>=2.9.11",
    "fastapi-mail",
]
