"""add placement_cycles dept_cycle_enrollments system_configs

Revision ID: c1170775c357
Revises: 780abe6d3d4d
Create Date: 2026-03-08 13:13:35.600165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1170775c357'
down_revision: Union[str, Sequence[str], None] = '780abe6d3d4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('placement_cycles',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_placement_cycles'))
    )
    op.create_index(op.f('ix_placement_cycles_name'), 'placement_cycles', ['name'], unique=True)
    op.create_index(op.f('ix_placement_cycles_status'), 'placement_cycles', ['status'], unique=False)
    op.create_table('system_configs',
    sa.Column('ai_model', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('login_rate_limit', sa.Integer(), nullable=False),
    sa.Column('login_rate_window', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_configs'))
    )
    op.create_table('dept_cycle_enrollments',
    sa.Column('cycle_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('application_open', sa.DateTime(timezone=True), nullable=False),
    sa.Column('application_close', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['placement_cycles.id'], name=op.f('fk_dept_cycle_enrollments_cycle_id')),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_dept_cycle_enrollments_department_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dept_cycle_enrollments')),
    sa.UniqueConstraint('cycle_id', 'department_id', name=op.f('uq_dept_cycle_enrollments_cycle_id'))
    )
    op.create_index(op.f('ix_dept_cycle_enrollments_cycle_id'), 'dept_cycle_enrollments', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_dept_cycle_enrollments_department_id'), 'dept_cycle_enrollments', ['department_id'], unique=False)
    op.add_column('offer_history', sa.Column('changed_by', sa.UUID(), nullable=True))
    op.add_column('offer_history', sa.Column('old_status', sa.String(length=50), nullable=False))
    op.add_column('offer_history', sa.Column('new_status', sa.String(length=50), nullable=False))
    op.add_column('offer_history', sa.Column('reason', sa.Text(), nullable=True))
    op.add_column('offer_history', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('offer_history', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_index(op.f('ix_offer_history_status'), table_name='offer_history')
    op.create_index(op.f('ix_offer_history_new_status'), 'offer_history', ['new_status'], unique=False)
    op.create_index(op.f('ix_offer_history_offer_id'), 'offer_history', ['offer_id'], unique=False)
    op.create_foreign_key(op.f('fk_offer_history_changed_by'), 'offer_history', 'users', ['changed_by'], ['id'])
    op.drop_column('offer_history', 'status')
    op.add_column('tpo_coordinators', sa.Column('name', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_tpo_coordinators_department_id'), 'tpo_coordinators', ['department_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tpo_coordinators_department_id'), table_name='tpo_coordinators')
    op.drop_column('tpo_coordinators', 'name')
    op.add_column('offer_history', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_offer_history_changed_by'), 'offer_history', type_='foreignkey')
    op.drop_index(op.f('ix_offer_history_offer_id'), table_name='offer_history')
    op.drop_index(op.f('ix_offer_history_new_status'), table_name='offer_history')
    op.create_index(op.f('ix_offer_history_status'), 'offer_history', ['status'], unique=False)
    op.drop_column('offer_history', 'updated_at')
    op.drop_column('offer_history', 'created_at')
    op.drop_column('offer_history', 'reason')
    op.drop_column('offer_history', 'new_status')
    op.drop_column('offer_history', 'old_status')
    op.drop_column('offer_history', 'changed_by')
    op.drop_index(op.f('ix_dept_cycle_enrollments_department_id'), table_name='dept_cycle_enrollments')
    op.drop_index(op.f('ix_dept_cycle_enrollments_cycle_id'), table_name='dept_cycle_enrollments')
    op.drop_table('dept_cycle_enrollments')
    op.drop_table('system_configs')
    op.drop_index(op.f('ix_placement_cycles_status'), table_name='placement_cycles')
    op.drop_index(op.f('ix_placement_cycles_name'), table_name='placement_cycles')
    op.drop_table('placement_cycles')
    # ### end Alembic commands ###
