"""initial schema

Revision ID: e1a9d7e51bb4
Revises: 
Create Date: 2026-03-06 07:21:52.307163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1a9d7e51bb4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_table('departments',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments')),
    sa.UniqueConstraint('name', name=op.f('uq_departments_name'))
    )
    op.create_table('roles',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_role_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_table('companies',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_companies_user_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies')),
    sa.UniqueConstraint('user_id', name=op.f('uq_companies_user_id'))
    )
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_table('students',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('enrollment_number', sa.String(length=50), nullable=False),
    sa.Column('cgpa', sa.Float(), nullable=False),
    sa.Column('tenth_percentage', sa.Float(), nullable=False),
    sa.Column('twelfth_percentage', sa.Float(), nullable=False),
    sa.Column('backlog_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_students_department_id')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_students_user_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_students')),
    sa.UniqueConstraint('user_id', name=op.f('uq_students_user_id'))
    )
    op.create_index(op.f('ix_students_department_id'), 'students', ['department_id'], unique=False)
    op.create_index(op.f('ix_students_enrollment_number'), 'students', ['enrollment_number'], unique=True)
    op.create_table('study_materials',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_study_materials_created_by')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_materials'))
    )
    op.create_index(op.f('ix_study_materials_category'), 'study_materials', ['category'], unique=False)
    op.create_table('tpo_coordinators',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_tpo_coordinators_department_id')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tpo_coordinators_user_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tpo_coordinators')),
    sa.UniqueConstraint('user_id', name=op.f('uq_tpo_coordinators_user_id'))
    )
    op.create_table('blacklists',
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('blacklisted_by', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['blacklisted_by'], ['users.id'], name=op.f('fk_blacklists_blacklisted_by')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_blacklists_company_id')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_blacklists_student_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blacklists'))
    )
    op.create_index(op.f('ix_blacklists_blacklisted_by'), 'blacklists', ['blacklisted_by'], unique=False)
    op.create_index(op.f('ix_blacklists_company_id'), 'blacklists', ['company_id'], unique=False)
    op.create_index(op.f('ix_blacklists_student_id'), 'blacklists', ['student_id'], unique=False)
    op.create_table('company_documents',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_company_documents_company_id')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_company_documents_uploaded_by')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_documents'))
    )
    op.create_index(op.f('ix_company_documents_company_id'), 'company_documents', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_documents_document_type'), 'company_documents', ['document_type'], unique=False)
    op.create_table('company_recruiters',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_company_recruiters_company_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_recruiters'))
    )
    op.create_index(op.f('ix_company_recruiters_email'), 'company_recruiters', ['email'], unique=False)
    op.create_table('material_access',
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['study_materials.id'], name=op.f('fk_material_access_material_id')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_material_access_student_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_material_access'))
    )
    op.create_table('placement_drives',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('drive_date', sa.DateTime(), nullable=False),
    sa.Column('registration_deadline', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_placement_drives_company_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_placement_drives'))
    )
    op.create_index(op.f('ix_placement_drives_status'), 'placement_drives', ['status'], unique=False)
    op.create_table('resumes',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_resumes_student_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resumes'))
    )
    op.create_index(op.f('ix_resumes_student_id'), 'resumes', ['student_id'], unique=False)
    op.create_table('student_documents',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_student_documents_student_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_documents'))
    )
    op.create_index(op.f('ix_student_documents_document_type'), 'student_documents', ['document_type'], unique=False)
    op.create_table('student_skills',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('skill_name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_student_skills_student_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_skills'))
    )
    op.create_table('jobs',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('drive_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=False),
    sa.Column('application_deadline', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_jobs_company_id')),
    sa.ForeignKeyConstraint(['drive_id'], ['placement_drives.id'], name=op.f('fk_jobs_drive_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.create_index(op.f('ix_jobs_company_id'), 'jobs', ['company_id'], unique=False)
    op.create_index(op.f('ix_jobs_title'), 'jobs', ['title'], unique=False)
    op.create_table('resume_ai_analysis',
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('ats_score', sa.Integer(), nullable=False),
    sa.Column('detected_skills', sa.JSON(), nullable=False),
    sa.Column('skill_gaps', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name=op.f('fk_resume_ai_analysis_resume_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resume_ai_analysis'))
    )
    op.create_table('resume_versions',
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name=op.f('fk_resume_versions_resume_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resume_versions'))
    )
    op.create_table('interview_rounds',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('round_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_interview_rounds_job_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interview_rounds'))
    )
    op.create_table('job_applications',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_applications_job_id')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_job_applications_student_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_applications'))
    )
    op.create_index(op.f('ix_job_applications_job_id'), 'job_applications', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_applications_status'), 'job_applications', ['status'], unique=False)
    op.create_index(op.f('ix_job_applications_student_id'), 'job_applications', ['student_id'], unique=False)
    op.create_table('job_eligibilities',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('min_cgpa', sa.Float(), nullable=False),
    sa.Column('max_backlogs', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_job_eligibilities_department_id')),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_eligibilities_job_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_eligibilities'))
    )
    op.create_index(op.f('ix_job_eligibilities_job_id'), 'job_eligibilities', ['job_id'], unique=False)
    op.create_table('job_locations',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_locations_job_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_locations'))
    )
    op.create_table('job_skills',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('skill_name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_skills_job_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_skills'))
    )
    op.create_index(op.f('ix_job_skills_skill_name'), 'job_skills', ['skill_name'], unique=False)
    op.create_table('application_stage_history',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('interview_round_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['job_applications.id'], name=op.f('fk_application_stage_history_application_id')),
    sa.ForeignKeyConstraint(['interview_round_id'], ['interview_rounds.id'], name=op.f('fk_application_stage_history_interview_round_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_stage_history'))
    )
    op.create_table('interview_feedback',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('interview_round_id', sa.UUID(), nullable=False),
    sa.Column('interviewer_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['job_applications.id'], name=op.f('fk_interview_feedback_application_id')),
    sa.ForeignKeyConstraint(['interview_round_id'], ['interview_rounds.id'], name=op.f('fk_interview_feedback_interview_round_id')),
    sa.ForeignKeyConstraint(['interviewer_id'], ['users.id'], name=op.f('fk_interview_feedback_interviewer_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interview_feedback'))
    )
    op.create_index(op.f('ix_interview_feedback_application_id'), 'interview_feedback', ['application_id'], unique=False)
    op.create_index(op.f('ix_interview_feedback_decision'), 'interview_feedback', ['decision'], unique=False)
    op.create_index(op.f('ix_interview_feedback_interview_round_id'), 'interview_feedback', ['interview_round_id'], unique=False)
    op.create_table('offers',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('offer_letter_url', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['job_applications.id'], name=op.f('fk_offers_application_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_offers'))
    )
    op.create_index(op.f('ix_offers_status'), 'offers', ['status'], unique=False)
    op.create_table('offer_history',
    sa.Column('offer_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], name=op.f('fk_offer_history_offer_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_offer_history'))
    )
    op.create_index(op.f('ix_offer_history_status'), 'offer_history', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_offer_history_status'), table_name='offer_history')
    op.drop_table('offer_history')
    op.drop_index(op.f('ix_offers_status'), table_name='offers')
    op.drop_table('offers')
    op.drop_index(op.f('ix_interview_feedback_interview_round_id'), table_name='interview_feedback')
    op.drop_index(op.f('ix_interview_feedback_decision'), table_name='interview_feedback')
    op.drop_index(op.f('ix_interview_feedback_application_id'), table_name='interview_feedback')
    op.drop_table('interview_feedback')
    op.drop_table('application_stage_history')
    op.drop_index(op.f('ix_job_skills_skill_name'), table_name='job_skills')
    op.drop_table('job_skills')
    op.drop_table('job_locations')
    op.drop_index(op.f('ix_job_eligibilities_job_id'), table_name='job_eligibilities')
    op.drop_table('job_eligibilities')
    op.drop_index(op.f('ix_job_applications_student_id'), table_name='job_applications')
    op.drop_index(op.f('ix_job_applications_status'), table_name='job_applications')
    op.drop_index(op.f('ix_job_applications_job_id'), table_name='job_applications')
    op.drop_table('job_applications')
    op.drop_table('interview_rounds')
    op.drop_table('resume_versions')
    op.drop_table('resume_ai_analysis')
    op.drop_index(op.f('ix_jobs_title'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_company_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('student_skills')
    op.drop_index(op.f('ix_student_documents_document_type'), table_name='student_documents')
    op.drop_table('student_documents')
    op.drop_index(op.f('ix_resumes_student_id'), table_name='resumes')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_placement_drives_status'), table_name='placement_drives')
    op.drop_table('placement_drives')
    op.drop_table('material_access')
    op.drop_index(op.f('ix_company_recruiters_email'), table_name='company_recruiters')
    op.drop_table('company_recruiters')
    op.drop_index(op.f('ix_company_documents_document_type'), table_name='company_documents')
    op.drop_index(op.f('ix_company_documents_company_id'), table_name='company_documents')
    op.drop_table('company_documents')
    op.drop_index(op.f('ix_blacklists_student_id'), table_name='blacklists')
    op.drop_index(op.f('ix_blacklists_company_id'), table_name='blacklists')
    op.drop_index(op.f('ix_blacklists_blacklisted_by'), table_name='blacklists')
    op.drop_table('blacklists')
    op.drop_table('tpo_coordinators')
    op.drop_index(op.f('ix_study_materials_category'), table_name='study_materials')
    op.drop_table('study_materials')
    op.drop_index(op.f('ix_students_enrollment_number'), table_name='students')
    op.drop_index(op.f('ix_students_department_id'), table_name='students')
    op.drop_table('students')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_table('departments')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
